### ISSUE TITLE
Unexpectedly high CPU memory usage

### ISSUE THREAD

**Issue by Nick-Eagles** [GYQ-form/HERGAST#1]
Hello,

Thanks for developing this great tool. I was following along the [clustering tutorial](https://github.com/GYQ-form/HERGAST/blob/main/Tutorial/Fine_scale_spatial_clustering.ipynb) with Visium HD data where I have ~450k bins. I was able to preprocess the data (including finding 200 PCs), construct a relational graph, and perform most of the training with `train_HERGAST.train_HERGAST(n_epochs=200)`, where all 200 epochs appear to complete. However, I get the error `RuntimeError: [enforce fail at alloc_cpu.cpp:117] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 576178240000 bytes. Error code 12 (Cannot allocate memory)`. I noticed in the paper, figure S1 suggests HERGAST should not get close to 512GB (the error message mentions ~576GB) at 450k bins, so I was wondering if I'm doing something incorrectly, or if you have an idea of what I can check. I'll attach the full output of my analysis (following the tutorial), including the traceback. Let me know if I can provide more information.

Best,
-Nick

```
2024-11-25 09:29:15.224375 | Building and preprocessing AnnData
2024-11-25 09:31:44.367334 | Constructing relational graph
------Calculating spatial graph...
Spatial graph contains 3603336 edges, 450417 cells.
8.0000 neighbors per cell on average.
------Calculating Expression simalarity graph...
Expression graph contains 3095481 edges, 450417 cells.
6.8725 neighbors per cell on average.
2024-11-25 10:03:29.926020 | Training model using num_batch_x_y=(7, 7)
Size of Input:  torch.Size([450417, 200])

  0%|          | 0/200 [00:00<?, ?it/s]
  0%|          | 1/200 [00:11<37:37, 11.34s/it]
[ More progress messages omitted for clarity]
100%|██████████| 200/200 [29:14<00:00,  8.77s/it]
Traceback (most recent call last):
  File "/dcs04/lieber/lcolladotor/Habenula_R01_LIBD4270/Habenula_Visium/code/10_HD_bin_level/05_hergast.py", line 97, in <module>
    train_HERGAST.train_HERGAST(n_epochs = 200)
  File "/jhpce/shared/libd/core/hergast/0.0.1/hergast_env/lib/python3.9/site-packages/HERGAST/Train_HERGAST.py", line 160, in train_HERGAST
    z, out, att1, att2 = model(data.x.cpu(), data.edge_index.cpu(), data.edge_type.cpu())
  File "/jhpce/shared/libd/core/hergast/0.0.1/hergast_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/jhpce/shared/libd/core/hergast/0.0.1/hergast_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/jhpce/shared/libd/core/hergast/0.0.1/hergast_env/lib/python3.9/site-packages/HERGAST/HERGAST.py", line 31, in forward
    h1, att1 = self.conv1(features, edge_index, edge_type, return_attention_weights=True)
  File "/jhpce/shared/libd/core/hergast/0.0.1/hergast_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/jhpce/shared/libd/core/hergast/0.0.1/hergast_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/jhpce/shared/libd/core/hergast/0.0.1/hergast_env/lib/python3.9/site-packages/torch_geometric/nn/conv/rgat_conv.py", line 350, in forward
    out = self.propagate(edge_index=edge_index, edge_type=edge_type, x=x,
  File "/tmp/torch_geometric.nn.conv.rgat_conv_RGATConv_propagate_2d0ha_by.py", line 218, in propagate
    out = self.message(
  File "/jhpce/shared/libd/core/hergast/0.0.1/hergast_env/lib/python3.9/site-packages/torch_geometric/nn/conv/rgat_conv.py", line 394, in message
    w = torch.index_select(w, 0, edge_type)
RuntimeError: [enforce fail at alloc_cpu.cpp:117] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 576178240000 bytes. Error code 12 (Cannot allocate memory)
```

**Comment by GYQ-form** [comment]
Dear Nick,

Thank you for reaching out and for your interest in our tool. First, I sincerely apologize for the delayed response—unfortunately, I did not receive a notification about this issue, and I have been occupied with other ongoing projects, which caused me to miss your message. I truly regret the inconvenience this may have caused.

This issue is attributed to the too-large default value of parameter `k_cutoff` in `HERGAST.utils.Cal_Spatial_Net(k_cutoff=8)` and `HERGAST.utils.Cal_Expression_Net(k_cutoff=6)`. This parameter largely influenced the CPU memory usage. However, it only has a minor influence on the model's performance when the data is large enough (above 300k spots/bins). So in the latest version, we have modified the default value of this parameter to `HERGAST.utils.Cal_Spatial_Net(k_cutoff=4)`  and `HERGAST.utils.Cal_Expression_Net(k_cutoff=3)`. You are supposed to find it work out now~ 

Feel free to further decrease this parameter when encountering extremely large dataset. As described before, when data volume becomes larger and larger, the model's performance also become more stable and not susceptible to this hyperparameter. 

Additionally, ensure that no other memory-intensive processes are running concurrently when running the pipeline. Thank you for your patience, and I appreciate your understanding.

Best regards,
Yuqiao
